apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlcoach
  labels:
    app: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: predictor
          image: terr0raidxd/mlcoach
          ports:
            - containerPort: 80
