import Head from 'next/head'
import styles from '../styles/Home.module.css'

import DnDFlow from '../components/Editor'
import printNodes from '../scripts/sumOp';

export default function Home() {


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
       <DnDFlow />
      </main>
    </div>
  )
}
